test-value: master:application-local.yml
test: 
  application-local: 1

logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG

spring:
  rabbitmq:
    host: localhost
    port: 5672
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tenki_jp
    username: root
    password: tronghoa
